name: "lastfm-jodie"
dataset: /data/gen-limnet/lastfm.csv
user_id_column: user_id
item_id_column: item_id
timestamp_column: timestamp

epochs: 300
train_ratio: 0.8
train_sequence_length: 1024
train_sequence_stride: 300
train_batch_size: 128
test_sequence_length: 1024
test_sequence_stride: 300
test_batch_size: 128

model_name: Jodie
model_attributes:
  embedding_size: 128
loss:
  
metrics:
  - l2_mrr
  - dot_product_mrr
  - dot_product_recall_at_1
  - dot_product_recall_at_10
  - l2_recall_at_1
  - l2_recall_at_10

l2: 0.00001
learning_rate: 0.01
