name: "wikipedia-multi-limnet"
dataset: /data/gen-limnet/wikipedia.csv
user_id_column: user_id
item_id_column: item_id
timestamp_column: timestamp

epochs: 300
train_ratio: 0.8
train_sequence_length: 128
train_heat_up_length: 0
train_sequence_stride: 30
train_batch_size: 1024
test_sequence_length: 128
test_heat_up_length: 96
test_sequence_stride: 30
test_batch_size: 2048

model_name: LiMNet
model_attributes:
  embedding_size: 16
  initialization: xavier_normal_
  nb_layers: 1
  normalize: False
  dropout_rate: 0.3
loss:
  dot_product_mse: 0.3
  mean_squared_error: 1
  expressivity_loss: 1

metrics:
  - l2_mrr
  - dot_product_mrr
  - dot_product_recall_at_1
  - dot_product_recall_at_10
  - l2_recall_at_1
  - l2_recall_at_10

l2: 0.0001
learning_rate: 0.016
