dataset: /data/gen-limnet/wikipedia.csv
user_id_column: user_id
item_id_column: item_id
timestamp_column: timestamp
user_features:
  - delta_users
item_features:
  - delta_items

epochs: 200
train_ratio: 0.8
sequence_length: 128
heat_up_length: 96
sequence_stride: 30
train_batch_size: 1024
test_batch_size: 2048
training_heat_up: False

model_name: LiMNet
model_attributes:
  embedding_size: 16
  initialization: xavier_normal_
loss:
  dot_product_mse: 1
  expressivity_loss: 1

metrics:
  - mean_reciprocal_rank

l2: 0.001