dataset: /data/gen-limnet/wikipedia.csv
user_id_column: user_id
item_id_column: item_id
timestamp_column: timestamp

epochs: 400
train_ratio: 0.8
train_sequence_length: 1
train_sequence_stride: 1
train_batch_size: 32768
test_sequence_length: 1
test_sequence_stride: 1
test_batch_size: 8192

model_name: TrainableEmbeddings
model_attributes:
  embedding_size: 16
loss:
  dot_product_mse: 1
  expressivity_loss: 1

metrics:
  - l2_mrr
  - dot_product_mrr

l2: 0

learning_rate: 0.1
