dataset: /data/gen-limnet/wikipedia.csv
user_id_column: user_id
item_id_column: item_id
timestamp_column: timestamp

epochs: 400
train_ratio: 0.8
sequence_length: 1
sequence_stride: 1
train_batch_size: 32768
test_batch_size: 4096
heat_up_length: 0

model_name: TrainableEmbeddings
model_attributes:
  embedding_size: 16
loss:
  dot_product_mse: 1
  expressivity_loss: 1

metrics:
  - mean_reciprocal_rank

l2: 0