dataset: /data/gen-limnet/wikipedia.csv
user_id_column: user_id
item_id_column: item_id
timestamp_column: timestamp

epochs: 200
train_ratio: 0.8
sequence_length: 128
sequence_stride: 48
train_batch_size: 32
test_batch_size: 64

model_name: TrainableEmbeddings
model_attributes:
  embedding_size: 16
  # initialization: xavier_normal_
loss:
  dot_product_mse: 1
  expressivity_loss: 1

metrics:
  - mean_reciprocal_rank
